---
apiVersion: v1
kind: Namespace
metadata:
  name: witnetnamespace
  labels:
    name: witnetnamespace
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast
  namespace: witnetnamespace
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fast-storage
  namespace: witnetnamespace
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: min-max
  namespace: witnetnamespace
spec:
  limits:
    - max:
        memory: 4Gi
        cpu: "4"
      min:
        memory: 100M
        cpu: 100m
      type: Container
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: witnet-deployment
  namespace: witnetnamespace
  labels:
    app: witnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: witnet
  template:
    metadata:
      labels:
        app: witnet
    spec:
      containers:
        - name: "witnet"
          image: "alejandrosl/witnetcustom:latest"
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 250m
              memory: 256Mi
          volumeMounts:
            - name: witnet-persistent-storage
              mountPath: "/persistent"
      volumes:
        - name: witnet-persistent-storage
          persistentVolumeClaim:
            claimName: fast-storage
---
apiVersion: v1
kind: Service
metadata:
  name: witnetservice
  namespace: witnetnamespace
  labels:
    app: witnet
spec:
  type: NodePort
  selector:
    app: witnet
  ports:
    - protocol: TCP
      port: 21337
      targetPort: 21337
